title: Jorge Nachtigall # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Engineer Specialist ðŸ“Š <br>
  Creator of Coding Wave YT Channel ðŸŽ¥ <br>
  Game Dev Hobbyst ðŸŽ® <br>
  Retro Game Collector ðŸ‘¾ <br>
  <br>
  Links:<br>
  <a href="https://www.linkedin.com/in/jorgenachtigall/">LinkedIn</a>
  <br>
  <a href="https://github.com/JorgeNachtigall">Github</a>
  <br>
  <a href="https://www.youtube.com/@codingwave">Youtube Channel</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
